#!/usr/bin/perl
#
#  Alter the message before it is archived or delivered to add headers to it.
#
#  We always add headers to identify where the mail came from, and in the
# case of a rejected message we add the rejection reason too.
#
# Steve
# --




sub hook_data_post
{
    my ( $self, $transaction ) = (@_);

    #
    # get the sender + ip + helo name for logging.
    #
    my $remote_ip   = $self->qp->connection->remote_ip;
    my $remote_host = $self->qp->connection->remote_host;
    my $helo        = $self->qp->connection->hello_host;

    #
    # MAIL FROM / RCPT TO values
    #
    my $from = $transaction->get("MAIL-FROM" );
    my $to   = $transaction->get("RCPT-TO" );

    #
    # Store hosts.
    #
    $transaction->header->add( 'X-HELO',        $helo );
    $transaction->header->add( 'X-REMOTE-IP',   $remote_ip );
    $transaction->header->add( 'X-REMOTE-HOST', $remote_host );

    #
    # Store sender/recipient
    #
    $transaction->header->add( 'X-MAIL-FROM', $from );
    $transaction->header->add( 'X-RCPT-TO',   $to );

    #
    #  If rejected store the reasons.
    #
    if ( ( $transaction->notes("reject") || 0 ) == 1 )
    {
        my $reason = $transaction->notes("reason")  || "Unknown reason";
        my $plugin = $transaction->notes("blocker") || "Unknown";

        $transaction->header->add( 'X-REJECT-REASON', $reason );
        $transaction->header->add( 'X-REJECT-PLUGIN', $plugin );
    }


    #
    #  All done
    #
    return DECLINED;
}
