#!/usr/bin/perl -w
#
#  Blacklist plugin
#
# Steve
# --
#



use Qpsmtpd::Constants;




=begin doc

  Blacklist on a per-domain basis.

=end doc

=cut

sub hook_data_post
{
    my ( $self, $transaction ) = (@_);

    #
    # Get the sending IP address.
    #
    my $remote_ip = $self->qp->connection->remote_ip;

    #
    # Get the domain this mail is for - this domain is setup
    # in the 'test_recipient' plugin
    #
    my $domain = $transaction->notes("domain") || undef;
    return DECLINED unless ( defined($domain) );

    #
    #  Is the IP blacklisted?
    #
    if ( ( -e "/srv/$domain/blacklisted/ips/$remote_ip" ) ||
         ( -e "/srv/_global_/blacklisted/ips/$remote_ip" ) )
    {
        $transaction->notes( "reject", 1 );
        $transaction->notes( "reason",
                             "IP address $remote_ip locally blacklisted" );

        return DECLINED;
    }

    #
    # Get the sender address, stripping brackets if present
    #
    my $sender = $transaction->notes("MAIL-FROM");
    $sender =~ s/^<//g;
    $sender =~ s/>$//g;

    #
    #  Is the sender blacklisted?
    #
    if ( length($sender) &&
         ( ( -e "/srv/$domain/blacklisted/senders/$sender" ) ||
           ( -e "/srv/_global_/blacklisted/senders/$sender" ) ) )
    {

        #
        #  OK this was from a whitelisted sender, remove the note.
        #
        $transaction->notes( "reject", 1 );
        $transaction->notes( "reason", "Mail from $sender is not welcome here" );
        return DECLINED;
    }


    return DECLINED;
}
